"""
Interactive configuration helper for population_metrics repo.
Allows user to either:
1. Auto-generate offense lists from selection_criteria.xlsx (default)
2. Manually enter specific offense codes
"""

import pandas as pd
from pathlib import Path
import sys

# Project paths
project_root = Path(__file__).parent.parent
data_dir = project_root / "data"
external_dir = project_root / "external_repos" / "population_metrics"

def load_selection_criteria():
    """Load offense tables from selection_criteria.xlsx"""
    try:
        selection_path = data_dir / "selection_criteria.xlsx"
        df = pd.read_excel(selection_path, sheet_name='Penal codes')
        return df
    except FileNotFoundError:
        print("⚠️  Warning: selection_criteria.xlsx not found in data/ folder")
        return None

def auto_generate_offense_lists(selection_df):
    """Generate violent/nonviolent lists from selection_criteria.xlsx"""
    print("\n" + "="*70)
    print("AUTO-GENERATING OFFENSE LISTS FROM SELECTION_CRITERIA.XLSX")
    print("="*70)
    
    # Table B = Violent felonies
    violent_codes = selection_df[selection_df['Table'] == 'Table B']['Offenses'].tolist()
    
    # Table A (not in B) = Serious but nonviolent
    table_a_codes = selection_df[selection_df['Table'] == 'Table A']['Offenses'].tolist()
    nonviolent_codes = [code for code in table_a_codes if code not in violent_codes]
    
    # Clean up codes (remove spaces, convert to string)
    violent_codes = [str(code).strip() for code in violent_codes]
    nonviolent_codes = [str(code).strip() for code in nonviolent_codes]
    
    print(f"\n✓ Violent codes (Table B): {len(violent_codes)} offenses")
    print(f"  Sample: {violent_codes[:5]}")
    
    print(f"\n✓ Nonviolent codes (Table A, not in B): {len(nonviolent_codes)} offenses")
    print(f"  Sample: {nonviolent_codes[:5]}")
    
    return violent_codes, nonviolent_codes

def manual_entry_offense_lists():
    """Allow user to manually enter offense codes"""
    print("\n" + "="*70)
    print("MANUAL OFFENSE CODE ENTRY")
    print("="*70)
    
    print("\nEnter VIOLENT offense codes (comma-separated):")
    print("Example: 187, 211, 245, 261")
    violent_input = input("Violent codes: ").strip()
    violent_codes = [code.strip() for code in violent_input.split(',') if code.strip()]
    
    print("\nEnter NONVIOLENT offense codes (comma-separated):")
    print("Example: 459, 484, 10851, 496")
    nonviolent_input = input("Nonviolent codes: ").strip()
    nonviolent_codes = [code.strip() for code in nonviolent_input.split(',') if code.strip()]
    
    print(f"\n✓ Violent codes entered: {len(violent_codes)}")
    print(f"  {violent_codes}")
    
    print(f"\n✓ Nonviolent codes entered: {len(nonviolent_codes)}")
    print(f"  {nonviolent_codes}")
    
    return violent_codes, nonviolent_codes

def create_config_file(violent_codes, nonviolent_codes):
    """Generate config_custom.py file for population_metrics"""
    
    config_content = f'''"""
Custom configuration for population_metrics
Auto-generated by scripts/01_configure_population_metrics.py
"""

# Profile: DEV = local files, PROD = GitHub URLs
CFG_PROFILE = "DEV"

# File paths (relative to this config file)
PATHS = {{
    "demographics": "../../data/demographics.csv",
    "current_commitments": "../../data/current_commits.csv",
    "prior_commitments": "../../data/prior_commits.csv"
}}

# Column mappings (None = skip that metric)
COLS = {{
    # Identifiers
    'id': 'cdcno',
    
    # Sentence information (from demographics)
    'current_sentence_months': 'aggregate sentence in months',
    'completed_months': None,  # Not available
    'past_time_months': None,  # Not available
    
    # Time tracking
    'offense_begin_date': 'offense begin date',
    'release_date': 'expected release date',
    
    # Demographics
    'age_years': None,  # Not available - age metric will be skipped
    
    # Offense information (from current_commits and prior_commits)
    'offense_code': 'offense',
    'offense_description': 'offense description',
    'offense_category': 'offense category',
    
    # Prison flag
    'in_prison': 'in prison'
}}

# Offense classification lists
OFFENSE_LISTS = {{
    'violent': {violent_codes},
    'nonviolent': {nonviolent_codes}
}}

# Defaults for missing data
DEFAULTS = {{
    # Time calculations
    'months_elapsed_total': None,  # Will be calculated from dates if available
    
    # Frequency bounds (skipped - no "time outside prison" data)
    'freq_min_rate': 0.0,
    'freq_max_rate': 0.05,
    
    # Age bounds (skipped - no age data)
    'age_min': 18,
    'age_max': 90,
    
    # Require time fields for processing?
    'require_time_fields': False  # Set to False since some time data missing
}}

# Metric weights (for suitability score)
# Positive weight = higher value is better (e.g., more nonviolent)
# Negative weight = higher value is worse (e.g., more violent)
METRIC_WEIGHTS = {{
    'desc_nonvio_curr': +1.0,    # % current offenses nonviolent (GOOD)
    'desc_nonvio_past': +1.0,    # % past offenses nonviolent (GOOD)
    'severity_trend': +1.0,      # Getting less violent over time (GOOD)
    'age': -0.5,                 # Younger = higher risk (BAD) - will be skipped
    'freq_violent': -1.0,        # Higher violent offense rate (BAD) - will be skipped
    'freq_total': -0.5,          # Higher total offense rate (BAD) - will be skipped
}}
'''
    
    # Write to external_repos/population_metrics/config_custom.py
    config_path = external_dir / "config_custom.py"
    
    with open(config_path, 'w') as f:
        f.write(config_content)
    
    print("\n" + "="*70)
    print("✓ CONFIG FILE CREATED")
    print("="*70)
    print(f"Location: {config_path}")
    print("\nThis file contains:")
    print("  • File paths to your CDCR data")
    print("  • Column name mappings")
    print("  • Offense classification lists (violent/nonviolent)")
    print("  • Metric weights for suitability scoring")

def modify_run_script():
    """Check if we need to modify run.py to use config_custom instead of config"""
    run_path = external_dir / "run.py"
    
    print("\n" + "="*70)
    print("CHECKING RUN.PY")
    print("="*70)
    
    try:
        with open(run_path, 'r') as f:
            content = f.read()
        
        if 'import config' in content and 'config_custom' not in content:
            print("\n⚠️  run.py currently imports 'config' (the default)")
            print("You have two options:")
            print("\nOption 1 (Recommended): Modify run.py to use config_custom")
            print("  Change: 'import config as CFG'")
            print("  To:     'import config_custom as CFG'")
            print("\nOption 2: Rename config_custom.py to config.py (overwrites default)")
            
            choice = input("\nModify run.py to use config_custom? (y/n): ").strip().lower()
            
            if choice == 'y':
                # Modify run.py
                new_content = content.replace('import config as CFG', 'import config_custom as CFG')
                new_content = new_content.replace('import config', 'import config_custom as CFG')
                
                with open(run_path, 'w') as f:
                    f.write(new_content)
                
                print("✓ run.py modified to use config_custom")
            else:
                print("⚠️  You'll need to manually edit run.py or rename config_custom.py")
        else:
            print("✓ run.py already configured correctly")
            
    except FileNotFoundError:
        print("⚠️  Warning: run.py not found")

def main():
    """Main interactive configuration process"""
    print("="*70)
    print("POPULATION METRICS CONFIGURATION HELPER")
    print("="*70)
    print("\nThis script will create config_custom.py for the population_metrics repo.")
    print("It will map your CDCR data columns and define offense classifications.")
    
    # Load selection criteria
    selection_df = load_selection_criteria()
    
    # Ask user how they want to define offense lists
    print("\n" + "="*70)
    print("OFFENSE CLASSIFICATION METHOD")
    print("="*70)
    
    if selection_df is not None:
        print("\nHow would you like to define violent/nonviolent offense codes?")
        print("\n1. AUTO (default): Use selection_criteria.xlsx")
        print("   - Table B = Violent felonies")
        print("   - Table A (not in B) = Nonviolent serious crimes")
        print(f"   - Total: {len(selection_df[selection_df['Table']=='Table B'])} violent + "
              f"{len(selection_df[selection_df['Table']=='Table A']) - len(selection_df[selection_df['Table']=='Table B'])} nonviolent")
        print("\n2. MANUAL: Enter specific offense codes yourself")
        
        choice = input("\nChoice (1/2) [default=1]: ").strip()
        
        if choice == '2':
            violent_codes, nonviolent_codes = manual_entry_offense_lists()
        else:
            violent_codes, nonviolent_codes = auto_generate_offense_lists(selection_df)
    else:
        print("\n⚠️  selection_criteria.xlsx not found. Falling back to manual entry.")
        violent_codes, nonviolent_codes = manual_entry_offense_lists()
    
    # Validate that we have codes
    if not violent_codes and not nonviolent_codes:
        print("\n✗ ERROR: No offense codes provided. Cannot proceed.")
        sys.exit(1)
    
    # Create config file
    create_config_file(violent_codes, nonviolent_codes)
    
    # Check if run.py needs modification
    modify_run_script()
    
    # Final instructions
    print("\n" + "="*70)
    print("✓ CONFIGURATION COMPLETE!")
    print("="*70)
    print("\nNext steps:")
    print("1. Review the config file if you want:")
    print(f"   {external_dir / 'config_custom.py'}")
    print("\n2. Run population_metrics:")
    print("   cd external_repos/population_metrics")
    print("   python run.py --out ../../outputs/population_metrics.csv")
    print("\n3. Check output:")
    print("   outputs/population_metrics.csv")
    
    print("\n" + "="*70)

if __name__ == "__main__":
    main()
